---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update packages
    tags: always
    apt:
      update_cache: yes
      upgrade: dist

- hosts: games
  become: true
  tasks:

  - name: install apache and php
    tags: apache,php,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
