---

- hosts: nodes
  become: true
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: latest

    - name: Use the k8s apt key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"

    - name: Install k8s apt sources
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        state: present
    
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: install k8s packages
      apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present
        update_cache: yes
